export interface User {
  creationDateTime:	string,
  creationUser:	string,
  department:	string,
  email:	string,
  enabled:	boolean,
  endDate:	string,
  gender:	string,
  id:	number,
  lastUpdateDateTime:	string,
  lastUpdateUser:	string,
  firstName: string,
  lastName: string,
  name:	string,
  password:	string,
  phone:	string,
  roles:	any[],
  startDate:	string,
  username:	string,
  photoPath: string;
}
